services:
  mongodb:
    build:
      context: ./api_dados
      dockerfile: Dockerfile.mongo
    container_name: mongodb_cinema
    networks:
      - cinema-network

  api:
    build:
      context: ./api_dados
      dockerfile: Dockerfile
    container_name: api_cinema
    environment:
      - MONGO_URL=mongodb://mongodb:27017/cinema
    depends_on:
      - mongodb
    networks:
      - cinema-network

  interface:
    build:
      context: ./interface
      dockerfile: Dockerfile.interface
    container_name: interface_cinema
    ports:
      - "7792:7792"
    environment:
      - API_URL=http://api_cinema:7789
    depends_on:
      - api
    networks:
      - cinema-network

networks:
  cinema-network:
    driver: bridge
